[package]
name = "blart"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
sptr = "0.3.2"

[dependencies.tinyvec]
version = "1.6.0"
features = ["std", "rustc_1_57"]

[features]
nightly = []

[dev-dependencies]
argh = "0.1.10"
criterion = { version = "0.4.0", features = ["html_reports"] }
dhat = "0.3.2"
rustc-hash = "1.1.0"

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dev-dependencies]
criterion-perf-events = "0.3.0"
perfcnt = "0.8.0"

[[bench]]
name = "map_apis"
harness = false
