[package]
name = "rad-tree"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies.smallvec]
version = "1.8.0"
features = ["union", "const_generics"]

[dev-dependencies]
argh = "0.1.7"
