[toolchain]
channel = "nightly-2022-04-20"
components = [
    "rustfmt",
    "rust-src",
    "rust-analyzer-preview",
    "rust-docs",
    "llvm-tools-preview",
    "clippy",
    "rust-analysis",
    "miri",
]
