name: Documentation

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build Documentation
        run: cargo doc --workspace --no-deps --all-features

      - name: Prepare to publish
        run: ./scripts/prep_documentation.sh

      - name: Publish to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/doc
          clean: true
          single-commit: true
